# use deta base

@startuml
class User {
    String key = self.email
    String email
    String username
    String password: hash.sha256.hexdiagest
    String expiredTime: format(YYYY-MM-DDThh:mm:ss)
    String accessToken: hash.sha256.hexdiagest
    String teamKey: Team.key
    Array[Team.key] historyTeamKey
}

class Team {
    String key = self.gameCode
    String gameCode
    String teamName
    Array[{String levelid, int spendTime: milisecond}] spendTimes
    String teamStatus: ["pending", "fin", "alive"]
    String nowLevelKey
    Array[User.key] member
}

class Level {
    String key
    String levelName
    Array[Hint.key] levelHints
    String answer
    String levelToken
    String nextLevelToken
}

class Hint {
    String key
    String hintName
    String hintContent
}

class Drama {
    String key
    Array[{speaker, speakContent, imgId}] dramaContents
    String dramaToken
    String nextDramaKey
}

@enduml
